version: '3.7'

services: 
    servers:
        container_name: imetatron_servers
        build: ./build
        ports:  
            - 80:80
            - 8081:8081
            - 6379:6379
        volumes:
            - ./www/:/var/www/

